name: Build & Deploy Static Site

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Locate Generator
        id: locate_generator
        run: |
          echo "GENERATOR=$(git config --file .gitmodules --get-regexp path | awk '{ print $2 }' | grep generator)" >> $GITHUB_OUTPUT

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        env:
          GENERATOR: ${{ steps.locate_generator.outputs.GENERATOR }}
        run: |
          sudo apt install pandoc &&
          pip install -r $GENERATOR/script/requirements.txt

      - name: Generate site
        env:
          GENERATOR: ${{ steps.locate_generator.outputs.GENERATOR }}
        run: |
          python $GENERATOR/script/generate.py

      - name: Upload HTML output
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
