name: Build & Deploy Static Site

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r generate/requirements.txt

      - name: Generate site
        run: |
          python generate/generate.py

      - name: Upload HTML output
        uses: actions/upload-pages-artifact@v4
        with:
          path: static

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
